[package]
name = "lexer"
authors = [
  "Pavel Grigorenko <GrigorenkoPV@niuitmo.ru>",
  "Jegor Popow <juicedogegor@gmail.com>",
]
version.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
common.path = "../common"
phf = { version = "0.13.1", features = ["macros"] }
unicode-ident = "1.0.24"

[dev-dependencies]
testing.path = "../testing"
