routine main() is
  var кошка is 1;
  var ねこ is 2;
  var π is 3;
  var α is 0;
  var 值 is 4;
  var 变量 is 5;
  var 고양이 is 6;
  var pequeño_pingüino is 7;
  var 'no_strings is 8;
  var _ is 9;
  α := кошка + ねこ;
  print α;
  print π;
  print 值;
  print 变量;
  print 고양이;
  print pequeño_pingüino;
  print 'no_strings;
end;
