[package]
name = "common"
description = "Definitions useful for other crates"
authors = [
  "Pavel Grigorenko <GrigorenkoPV@niuitmo.ru>",
  "Jegor Popow <juicedogegor@gmail.com>",
]
version.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true
