[package]
name = "parser"
authors = [
  "Pavel Grigorenko <GrigorenkoPV@niuitmo.ru>",
  "Jegor Popow <juicedogegor@gmail.com>",
]
version.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
common.path = "../common"
lexer.path = "../lexer"
culpa.workspace = true
derive-where.workspace = true

[dev-dependencies]
testing.path = "../testing"
