[package]
name = "codegen"
description = "Definitions useful for other crates"
authors = [
  "Jegor Popow <juicedogegor@gmail.com>",
  "Andrew Vlasenkov <andrew.vlasenkov70@gmail.com>",
]
version.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
ast.path = "../ast"
common.path = "../common"
